"""empty message

Revision ID: 040c0f0db6f6
Revises: 
Create Date: 2021-01-06 12:01:45.576494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040c0f0db6f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('settings', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('players', sa.String(), nullable=False),
    sa.Column('alive', sa.String(), nullable=False),
    sa.Column('purged', sa.String(), nullable=False),
    sa.Column('targets', sa.String(), nullable=False),
    sa.Column('killCount', sa.String(), nullable=False),
    sa.Column('killLog', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pastgames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('settings', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('players', sa.String(), nullable=False),
    sa.Column('survivalWinner', sa.String(), nullable=False),
    sa.Column('killWinner', sa.String(), nullable=False),
    sa.Column('killLog', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('games', sa.String(), nullable=False),
    sa.Column('theme', sa.Integer(), nullable=False),
    sa.Column('stats', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('pastgames')
    op.drop_table('games')
    # ### end Alembic commands ###
