"""empty message

Revision ID: 068430fde388
Revises: 
Create Date: 2021-01-06 18:02:33.409162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068430fde388'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pastgames', sa.Column('killWinners', sa.String(), nullable=False))
    op.drop_column('pastgames', 'killWinner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pastgames', sa.Column('killWinner', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('pastgames', 'killWinners')
    # ### end Alembic commands ###
